### ISSUE TITLE
Search gives a 500 Internal with a timeout for mirroring registry

### ISSUE THREAD

**Issue by michaelhwalther** [atc-/docker-registry-web#119]
Typing a term in the "search images.." textbox results in a wait of 20 sec or so, and then a "500 Internal Server Error" with a "NOT_FOUND" error code.

Please find an excerpt from the log (querying for term "owncloud", which apparently finds a result including mmckeen/owncloud) below.
It seems that the error occurs when trying to determine the tags for the repository on the remote/mirrored repository. The tags URL as given (http://dregistry:5000/v1/repositories/mmckeen/owncloud/tags) indeed gives a 404 - NOT FOUND.

2014-12-09 16:46:57,668 [http-bio-8080-exec-4] INFO  web.RepositoryService  - Getting tags for mmckeen/owncloud
2014-12-09 16:46:57,668 [http-bio-8080-exec-4] INFO  web.RepositoryService  - tags url http://dregistry:5000/v1/repositories/mmckeen/owncloud/tags
2014-12-09 16:46:58,365 [http-bio-8080-exec-4] ERROR errors.GrailsExceptionResolver  - HttpResponseException occurred when processing request: [GET] /search/search
NOT FOUND. Stacktrace follows:
groovyx.net.http.HttpResponseException: NOT FOUND
	at groovyx.net.http.HTTPBuilder.defaultFailureHandler(HTTPBuilder.java:652)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:508)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:441)
	at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:390)
	at docker.registry.web.RepositoryService.$tt__getTags(RepositoryService.groovy:69)
	at docker.registry.web.RepositoryService$_tt__search_closure10_closure15_closure16.doCall(RepositoryService.groovy:55)
	at docker.registry.web.RepositoryService$_tt__search_closure10_closure15.doCall(RepositoryService.groovy:54)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:508)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:441)
	at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:390)
	at docker.registry.web.RepositoryService.$tt__search(RepositoryService.groovy:51)
	at docker.registry.web.SearchService$_$tt__searchAll_closure2.doCall(SearchService.groovy:16)
	at docker.registry.web.SearchService.$tt__searchAll(SearchService.groovy:15)
	at docker.registry.web.SearchController.search(SearchController.groovy:12)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

This is using 0.96.0 in a container. Docker registry is running on same host in separate container. All hostnames are explicit (no "localhost" used).

**Comment by atc-** [comment]
Does the registry have a search backend?

**Comment by michaelhwalther** [comment]
I have not configured a search backend specifically; I'm using the official Docker registry container 0.96.0 "as is". The only configuration change is the addition of mirroring for the public Docker registry (as described above)

**Comment by ascheman** [comment]
I have the same problem here, will provide a fix which at least catches the 404 response from the registry "GET .../tags" request.

**Comment by atc-** [comment]
Excellent, thank you!
